title: "rob.tech"
author: "Robert Habermeier"
description: ""
permalink: /blog/:title/
lang: "en"
excerpt_separator: "\n\n\n"
date_format: "%B %d, %Y"
url: "https://rob.tech"

# Layout

fixed_menu: true
sidebar: false               # show a sidebar instead of the usual header
show_excerpts: true          # show article excerpts on the home page
show_related: false          # show the previous and next links after every post
show_description: true       # show the site description in the sidebar
show_title: false            # always keep the site title visible

# MathJax, please
mathjax: true

highlighter: rouge

# Menu

external:                    # see http://fontawesome.com/icons
  - {title: Github, icon: github-square, url: "https://github.com/rphmeier"}
  - {title: Twitter, icon: twitter-square, url: "https://twitter.com/rphmeier"}
  - {title: RSS, icon: rss-square, url: "/feed.xml"}

navigation:
  - {file: "index.html"}
  - {file: "blog.html"}

plugins:
 - jekyll-feed
 - jekyll-postcss

postcss:
 cache: false
